# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_path',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
